package com.example.focusguardian.navigation

object Routes {
    const val AUTH = "auth"
    const val SPLASH = "splash"
    const val LOGIN = "login"
    const val CREATE = "create"
    const val ROLE = "role"
    const val INTEREST = "interest"
    const val REFINE_INTEREST = "refine_interest"
    const val REFINE_EDUCATIONAL_INTEREST = "refine_educational_interest"
    const val FITNESS = "fitness"
    const val DASHBOARD = "dashboard"
    const val ADDICTION_SCORE = "addiction"
    const val SLEEP = "sleep"
    const val CHALLENGES = "challenges"
    const val ANALYTICS = "analytics"
    const val TIME_USED = "time_used"
    const val NOTIFICATIONS = "notifications"
    const val NO_SCROLL = "no_scroll"
    const val DEEP_FOCUS = "deep_focus"
    const val EARLY_SLEEP = "early_sleep"
    const val FIRST_STEP_BADGE = "first_step_badge"
    const val SLEEP_GUARDIAN_BADGE = "sleep_guardian_badge"
    const val THREE_DAY_STREAK_BADGE = "three_day_streak_badge"
    const val ZEN_MASTER_BADGE = "zen_master_badge"
    const val MAIN = "main"
    const val WALLPAPER = "wallpaper"
    const val PROFILE_SETTINGS = "profile_settings"
    const val MANAGE_APPS = "manage_apps"
}
